### ISSUE TITLE
list isn't showing all homes - the last one is cut off

### ISSUE THREAD

**Issue by tdugger** [mmonkey/Destinations#1]
Create a home and then do /homes.  It didn't show any homes for me.  Created another and then did /homes and only the first showed.

I think you need to remove the -1 from PaginatedList.subList() lines 83 and 84.  Removing those would show all homes.

**Comment by tdugger** [comment]
my suggestion probably isn't clear so here's what I changed the subList method to be..

```
public List<Text> subList(int fromIndex, int toIndex) {
    int from = ((this.size() - 1) > fromIndex) ? fromIndex : (this.size());
    int to = ((this.size() - 1) > toIndex) ? toIndex : (this.size());
    return this.items.subList(from, to);
}
```

**Comment by mmonkey** [comment]
I committed this change a few days ago, I just haven't recompiled the build. I will do that sometime this evening.

**Comment by tdugger** [comment]
Oh yeah, I see it now.  Change just wasn't in the source zip file.  Cool.

**Comment by NoobTaco** [comment]
Oops. . I just duped this bug. However, It is still not working
